### ISSUE TITLE
Member books a practice session.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/camden-curling-club#10]
**EPIC:** Bookings page.

**As a member, I would like to book a practice session so that I can attend at a time that suits me.**

**Acceptance Criteria (AC)**

- [x] AC-1: The bookings page will display a date-picker and a drop-down list of available practice session times.   

- [x] AC-2: A member can choose from 6 sessions and a message will confirm that the booking has been made. 

- [x] AC-3: A check box will allow a member to request a wheelchair accessible session.

**Tasks**

- [x] Task 1: Create bookings app.

- [x] Task 2: Models, views and urls.

- [x] Task 3: Templates and styling.

- [x] Task 4: Test and review.
