### ISSUE TITLE
Member modifies / cancels a practice session.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/camden-curling-club#11]
**EPIC:** Bookings page.

**As a member, I would like to amend or cancel a practice session so that I can change my plans.**

**Acceptance Criteria (AC)**

- [x] AC-1: When a member clicks on their booking, they will be given the option to cancel or amend the booking.

- [x] AC-2: A message will confirm that the new booking has been made.

- [x] AC-3: A message will confirm that the booking has been cancelled.

**Tasks**

- [x] Task 1: Create bookings app.

- [x] Task 2: Models, views and urls.

- [x] Task 3: Templates and styling.

- [x] Task 4: Test and review.
