### ISSUE TITLE
Member checks booking availability.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/camden-curling-club#12]
**EPIC:** Bookings page.

**As a member, I would like to know if the booking time I want is available so that I can make another choice if necessary.**

**Acceptance Criteria (AC)**

- [ ] AC-1: If a session time has already been booked then a message will display stating 'Not available, please select another session.'

**Tasks**

- [ ] Task 1: Create bookings app.

- [ ] Task 2: Models, views and urls.

- [ ] Task 3: Templates and styling.

- [ ] Task 4: Test and review.
