### ISSUE TITLE
Member adds images to the gallery.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/camden-curling-club#13]
**EPIC:** Gallery page.

**As a member, I would like to add images to the gallery so that I can share my curling experiences with other members.**

**Acceptance Criteria (AC)**

- [x] AC-1: A member can upload or delete an image.

- [x] AC-2: A member can upload, amend or delete a caption.

- [x] AC-3: A new image will not be made public until approved by the site administrator.

**Tasks**

- [x] Task 1: Create gallery app.

- [x] Task 2: Models, views and urls.

- [x] Task 3: Templates and styling.

- [x] Task 4: Test and review.
