### ISSUE TITLE
Gallery content management.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/camden-curling-club#14]
**EPIC:** Gallery page.

**As a site administrator, I would like to approve or delete images added to the gallery so that I can filter out any objectionable material.**

**Acceptance Criteria (AC)**

- [x] AC-1: They can approve an image/caption for public display.

- [x] AC-2: They can delete an image/caption.

**Tasks**

- [x] Task 1: Create gallery app.

- [x] Task 2: Models, views, urls.

- [x] Task 3: Templates and styling.

- [x] Task 4: Test and review.
