### ISSUE TITLE
Curling Network content management.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/camden-curling-club#15]
**EPIC:** Curling Network page.

**As a site administrator, I would like to manage content on the curling network page so that I can keep members informed of other curling venues.**

**Acceptance Criteria (AC)**

- [x] AC-1: Content categories are: club name, location, website, email and wheelchair accessibility.

- [x] AC-2: They can create content.

- [x] AC-3: They can read content.

- [x] AC-4: They can update content.

- [x] AC-5: They can delete content.

**Tasks**

- [x] Task 1: Create network app.

- [x] Task 2: Models, views and urls.

- [x] Task 3: Templates and styling.

- [x] Task 4: Test and review.
