### ISSUE TITLE
Site administration access.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/camden-curling-club#16]
**EPIC:** Site administration.

**As a site administrator, I would like to access the administrator panel so that I can manage the club membership and site's pages.**

**Acceptance Criteria (AC)**

- [x] AC-1: They will be able to log in to the administrator panel.

- [x] AC-2: They will be able to perform site administration functions.

**Tasks**

- [x] Task 1: Install django framework and confirm server connection.

- [x] Task 2: Ensure DATABASE and SECRET_KEY are added to env.py (.gitignore).

- [x] Task 3: Register gitpod and heroku as CSRF trusted origins.

- [x] Task 4: Create superuser and login to admin panel.
