### ISSUE TITLE
External Frameworks.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/camden-curling-club#20]
**Issue**

**Set up these key frameworks for project development:**

**Tasks**
- [x] Django for fullstack web framework.
- [x] Neon for postgres database.
- [x] Bootstrap for frontend HTML and CSS.
- [x] Heroku for project deployment.
- [x] Cloudinary for image storage.
