### ISSUE TITLE
Django Project Template.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/camden-curling-club#21]
**Issue:** 

**Set up base.html with header, nav bar and footer.**

**Tasks:**

- [x] Create and test base.html with basic styling.
- [x] Develop with Bootstrap.
- [x] Enhance CSS for base.html.
