### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/camden-curling-club#25]
**Issue:** 

**Undertake code validation and testing.**

**Tasks:**
- [x] Ensure functions and classes have docstrings.
- [x] Delete commented out code.
- [x] Create TESTING.md.
- [x] Complete **TESTING.md Checklist** issue.
