### ISSUE TITLE
Tracking README.md progress.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/camden-curling-club#27]
**Issue:** 
Create and update the README.md throughout project development.

**Tasks:**
- [x] Create README.md and TESTING.md along with formatting.
- [x] Ongoing update throughout project development.
- [x] Create README.md completion checklist.
