### ISSUE TITLE
Home page.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/camden-curling-club#34]
**EPIC: Home page.** 

**As a new user, I would like to land on an informative and engaging home page so that I can learn about the club.**

**Acceptance Criteria (AC)**

- [x] AC-1: They will be engaged by the style and informative content.

- [x] AC-2: Website meets accessibility standards for contrast.

**Tasks**

- [x] Task 1: Confirm content.

- [x] Task 2: Create home app and index.html.

- [x] Task 3: Styling.

- [ ] Task 4: Test and review.
