### ISSUE TITLE
README.md Checklist

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/camden-curling-club#39]
**Track README.md progress to completion.**

**Sections**
- [x] Project Purpose
- [x] Target Audience
- [x] UX
- [x] Initial Design and Wireframes
- [x] Colour Scheme
- [x] Typography
- [x] User Stories
- [x] Existing Features
- [x] Future Features
- [x] Tools & Technologies Used
- [x] Database Design
- [x] Agile Project Management
- [x] GitHub Projects
- [x] GitHub Issues
- [x] MoSCoW Prioritization
- [x] Testing (see TESTING.md)
- [x] Deployment
- [x] PostgreSQL Database
- [x] Cloudinary API
- [x] Heroku Deployment
- [x] Local Deployment
- [x] Cloning
- [x] Forking
- [x] Credits
- [x] Content
- [x] Media
- [x] Acknowledgements
