### ISSUE TITLE
User registration.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/camden-curling-club#5]
**EPIC:** User registration.

**As a new user, I would like to submit my contact details so that I can register my membership.**

**Acceptance Criteria (AC)**

- [x] AC-1: Upon submitting their details, a new user can register an account.

- [x] AC-2: They can then log in and see a welcome message.

- [x] AC-3: When logged in they can access all members' pages.

**Tasks**

- [x] Task 1: Install AllAuth.

- [x] Task 2: Amend AllAuth templates and project base.html.

- [x] Task 3: Adapt styling to match project.
