### ISSUE TITLE
Member log in.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/camden-curling-club#6]
**EPIC:** User log in or log out.

**As a member, I would like to enter my login details so that I can access the members' area.**

**Acceptance Criteria (AC)**

- [x] AC-1: When they log in they will see a welcome message.

- [x] AC-2: When logged in, the nav bar will enable them to access the FAQs, Bookings, Gallery and Curling Network pages.

**Tasks**

- [x] Task 1: Install AllAuth.

- [x] Task 2: Amend AllAuth templates and project base.html.

- [x] Task 3: Adapt styling to match project.
