### ISSUE TITLE
Member log out.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/camden-curling-club#7]
**EPIC:** User log in or log out.

**As a member, I would like to logout so that I can know my session has been closed securely.**

**Acceptance Criteria (AC)**

- [x] AC-1: When they log out they will be asked to confirm that they want to log out.

- [x] AC-2: When they log out they will see a message confirming that they have been logged out.

**Tasks**

- [x] Task 1: Install AllAuth.

- [x] Task 2: Amend AllAuth templates and project base.html.

- [x] Task 3: Adapt styling to match project.
