### ISSUE TITLE
Manage FAQs content.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/camden-curling-club#8]
**EPIC:** FAQs page.

**As a site administrator, I would like to manage content on the FAQs page so that I can provide information to members.**

**Acceptance Criteria (AC)**

- [x] AC-1: They can create FAQs content.

- [x] AC-2: They can read FAQs content.

- [x] AC-3: They can update FAQs content.

- [x] AC-4: They can delete FAQs content.

**Tasks**

- [x] Task 1: Create faqs app.

- [x] Task 2: Models, views and urls.

- [x] Task 3: Templates and styling.

- [x] Task 4:  Test and review.
