### ISSUE TITLE
Member suggests a question for FAQs.

### ISSUE THREAD

**Issue by Adam-Alive** [Adam-Alive/camden-curling-club#9]
**EPIC:** FAQs page.

**As a member, I would like to submit a question for display on the FAQs page.**

**Acceptance Criteria (AC)**

- [ ] AC-1: When a member is logged in they can fill in a submission form with a suggested question.

- [ ] AC-2: A message will display confirming that the submission has been accepted.

**Tasks**

- [x] Task 1: Create faqs app.

- [ ] Task 2: 

- [ ] Task 3: 

- [ ] Task 4:
